/*
 * This file is generated by jOOQ.
 */
package de.tum.jk.orm.pojos.unischema.tables.records;


import de.tum.jk.orm.pojos.unischema.tables.Hoeren;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HoerenRecord extends UpdatableRecordImpl<HoerenRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -813869565;

    /**
     * Setter for <code>unischema.hoeren.MatrNr</code>.
     */
    public void setMatrnr(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>unischema.hoeren.MatrNr</code>.
     */
    public Integer getMatrnr() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>unischema.hoeren.VorlNr</code>.
     */
    public void setVorlnr(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>unischema.hoeren.VorlNr</code>.
     */
    public Integer getVorlnr() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Hoeren.HOEREN.MATRNR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Hoeren.HOEREN.VORLNR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMatrnr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getVorlnr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMatrnr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getVorlnr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HoerenRecord value1(Integer value) {
        setMatrnr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HoerenRecord value2(Integer value) {
        setVorlnr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HoerenRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HoerenRecord
     */
    public HoerenRecord() {
        super(Hoeren.HOEREN);
    }

    /**
     * Create a detached, initialised HoerenRecord
     */
    public HoerenRecord(Integer matrnr, Integer vorlnr) {
        super(Hoeren.HOEREN);

        set(0, matrnr);
        set(1, vorlnr);
    }
}
