/*
 * This file is generated by jOOQ.
 */
package de.tum.jk.orm.pojos.unischema.tables.records;


import de.tum.jk.orm.pojos.unischema.tables.Voraussetzen;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VoraussetzenRecord extends UpdatableRecordImpl<VoraussetzenRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1364329569;

    /**
     * Setter for <code>unischema.voraussetzen.Vorgaenger</code>.
     */
    public void setVorgaenger(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>unischema.voraussetzen.Vorgaenger</code>.
     */
    public Integer getVorgaenger() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>unischema.voraussetzen.Nachfolger</code>.
     */
    public void setNachfolger(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>unischema.voraussetzen.Nachfolger</code>.
     */
    public Integer getNachfolger() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Voraussetzen.VORAUSSETZEN.VORGAENGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Voraussetzen.VORAUSSETZEN.NACHFOLGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getVorgaenger();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getNachfolger();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getVorgaenger();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getNachfolger();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VoraussetzenRecord value1(Integer value) {
        setVorgaenger(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VoraussetzenRecord value2(Integer value) {
        setNachfolger(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VoraussetzenRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VoraussetzenRecord
     */
    public VoraussetzenRecord() {
        super(Voraussetzen.VORAUSSETZEN);
    }

    /**
     * Create a detached, initialised VoraussetzenRecord
     */
    public VoraussetzenRecord(Integer vorgaenger, Integer nachfolger) {
        super(Voraussetzen.VORAUSSETZEN);

        set(0, vorgaenger);
        set(1, nachfolger);
    }
}
