/*
 * This file is generated by jOOQ.
 */
package de.tum.jk.orm.pojos.unischema.tables.records;


import de.tum.jk.orm.pojos.unischema.tables.Vorlesungen;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VorlesungenRecord extends UpdatableRecordImpl<VorlesungenRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -1425346014;

    /**
     * Setter for <code>unischema.Vorlesungen.VorlNr</code>.
     */
    public void setVorlnr(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>unischema.Vorlesungen.VorlNr</code>.
     */
    public Integer getVorlnr() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>unischema.Vorlesungen.Titel</code>.
     */
    public void setTitel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>unischema.Vorlesungen.Titel</code>.
     */
    public String getTitel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>unischema.Vorlesungen.SWS</code>.
     */
    public void setSws(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>unischema.Vorlesungen.SWS</code>.
     */
    public Integer getSws() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>unischema.Vorlesungen.gelesenVon</code>.
     */
    public void setGelesenvon(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>unischema.Vorlesungen.gelesenVon</code>.
     */
    public Integer getGelesenvon() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Vorlesungen.VORLESUNGEN.VORLNR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Vorlesungen.VORLESUNGEN.TITEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Vorlesungen.VORLESUNGEN.SWS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Vorlesungen.VORLESUNGEN.GELESENVON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getVorlnr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getSws();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getGelesenvon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getVorlnr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSws();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getGelesenvon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VorlesungenRecord value1(Integer value) {
        setVorlnr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VorlesungenRecord value2(String value) {
        setTitel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VorlesungenRecord value3(Integer value) {
        setSws(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VorlesungenRecord value4(Integer value) {
        setGelesenvon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VorlesungenRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VorlesungenRecord
     */
    public VorlesungenRecord() {
        super(Vorlesungen.VORLESUNGEN);
    }

    /**
     * Create a detached, initialised VorlesungenRecord
     */
    public VorlesungenRecord(Integer vorlnr, String titel, Integer sws, Integer gelesenvon) {
        super(Vorlesungen.VORLESUNGEN);

        set(0, vorlnr);
        set(1, titel);
        set(2, sws);
        set(3, gelesenvon);
    }
}
