/*
 * This file is generated by jOOQ.
 */
package de.tum.jk.orm.pojos.unischema;


import de.tum.jk.orm.pojos.unischema.tables.Assistenten;
import de.tum.jk.orm.pojos.unischema.tables.Hoeren;
import de.tum.jk.orm.pojos.unischema.tables.Professoren;
import de.tum.jk.orm.pojos.unischema.tables.Pruefen;
import de.tum.jk.orm.pojos.unischema.tables.Studenten;
import de.tum.jk.orm.pojos.unischema.tables.Voraussetzen;
import de.tum.jk.orm.pojos.unischema.tables.Vorlesungen;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>unischema</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ASSISTENTEN_BOSS = Indexes0.ASSISTENTEN_BOSS;
    public static final Index ASSISTENTEN_PRIMARY = Indexes0.ASSISTENTEN_PRIMARY;
    public static final Index HOEREN_PRIMARY = Indexes0.HOEREN_PRIMARY;
    public static final Index PROFESSOREN_PRIMARY = Indexes0.PROFESSOREN_PRIMARY;
    public static final Index PROFESSOREN_RAUM = Indexes0.PROFESSOREN_RAUM;
    public static final Index PRUEFEN_PRIMARY = Indexes0.PRUEFEN_PRIMARY;
    public static final Index STUDENTEN_PRIMARY = Indexes0.STUDENTEN_PRIMARY;
    public static final Index VORAUSSETZEN_PRIMARY = Indexes0.VORAUSSETZEN_PRIMARY;
    public static final Index VORLESUNGEN_PRIMARY = Indexes0.VORLESUNGEN_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ASSISTENTEN_BOSS = Internal.createIndex("Boss", Assistenten.ASSISTENTEN, new OrderField[] { Assistenten.ASSISTENTEN.BOSS }, false);
        public static Index ASSISTENTEN_PRIMARY = Internal.createIndex("PRIMARY", Assistenten.ASSISTENTEN, new OrderField[] { Assistenten.ASSISTENTEN.PERSNR }, true);
        public static Index HOEREN_PRIMARY = Internal.createIndex("PRIMARY", Hoeren.HOEREN, new OrderField[] { Hoeren.HOEREN.MATRNR, Hoeren.HOEREN.VORLNR }, true);
        public static Index PROFESSOREN_PRIMARY = Internal.createIndex("PRIMARY", Professoren.PROFESSOREN, new OrderField[] { Professoren.PROFESSOREN.PERSNR }, true);
        public static Index PROFESSOREN_RAUM = Internal.createIndex("Raum", Professoren.PROFESSOREN, new OrderField[] { Professoren.PROFESSOREN.RAUM }, true);
        public static Index PRUEFEN_PRIMARY = Internal.createIndex("PRIMARY", Pruefen.PRUEFEN, new OrderField[] { Pruefen.PRUEFEN.MATRNR, Pruefen.PRUEFEN.VORLNR }, true);
        public static Index STUDENTEN_PRIMARY = Internal.createIndex("PRIMARY", Studenten.STUDENTEN, new OrderField[] { Studenten.STUDENTEN.MATRNR }, true);
        public static Index VORAUSSETZEN_PRIMARY = Internal.createIndex("PRIMARY", Voraussetzen.VORAUSSETZEN, new OrderField[] { Voraussetzen.VORAUSSETZEN.VORGAENGER, Voraussetzen.VORAUSSETZEN.NACHFOLGER }, true);
        public static Index VORLESUNGEN_PRIMARY = Internal.createIndex("PRIMARY", Vorlesungen.VORLESUNGEN, new OrderField[] { Vorlesungen.VORLESUNGEN.VORLNR }, true);
    }
}
