/*
 * This file is generated by jOOQ.
 */
package de.tum.jk.orm.pojos.unischema;


import de.tum.jk.orm.pojos.unischema.tables.Assistenten;
import de.tum.jk.orm.pojos.unischema.tables.Hoeren;
import de.tum.jk.orm.pojos.unischema.tables.Professoren;
import de.tum.jk.orm.pojos.unischema.tables.Pruefen;
import de.tum.jk.orm.pojos.unischema.tables.Studenten;
import de.tum.jk.orm.pojos.unischema.tables.Voraussetzen;
import de.tum.jk.orm.pojos.unischema.tables.Vorlesungen;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in unischema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>unischema.Assistenten</code>.
     */
    public static final Assistenten ASSISTENTEN = de.tum.jk.orm.pojos.unischema.tables.Assistenten.ASSISTENTEN;

    /**
     * The table <code>unischema.hoeren</code>.
     */
    public static final Hoeren HOEREN = de.tum.jk.orm.pojos.unischema.tables.Hoeren.HOEREN;

    /**
     * The table <code>unischema.Professoren</code>.
     */
    public static final Professoren PROFESSOREN = de.tum.jk.orm.pojos.unischema.tables.Professoren.PROFESSOREN;

    /**
     * The table <code>unischema.pruefen</code>.
     */
    public static final Pruefen PRUEFEN = de.tum.jk.orm.pojos.unischema.tables.Pruefen.PRUEFEN;

    /**
     * The table <code>unischema.Studenten</code>.
     */
    public static final Studenten STUDENTEN = de.tum.jk.orm.pojos.unischema.tables.Studenten.STUDENTEN;

    /**
     * The table <code>unischema.voraussetzen</code>.
     */
    public static final Voraussetzen VORAUSSETZEN = de.tum.jk.orm.pojos.unischema.tables.Voraussetzen.VORAUSSETZEN;

    /**
     * The table <code>unischema.Vorlesungen</code>.
     */
    public static final Vorlesungen VORLESUNGEN = de.tum.jk.orm.pojos.unischema.tables.Vorlesungen.VORLESUNGEN;
}
