/*
 * This file is generated by jOOQ.
 */
package de.tum.jk.orm.pojos.unischema;


import de.tum.jk.orm.pojos.DefaultCatalog;
import de.tum.jk.orm.pojos.unischema.tables.Assistenten;
import de.tum.jk.orm.pojos.unischema.tables.Hoeren;
import de.tum.jk.orm.pojos.unischema.tables.Professoren;
import de.tum.jk.orm.pojos.unischema.tables.Pruefen;
import de.tum.jk.orm.pojos.unischema.tables.Studenten;
import de.tum.jk.orm.pojos.unischema.tables.Voraussetzen;
import de.tum.jk.orm.pojos.unischema.tables.Vorlesungen;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Unischema extends SchemaImpl {

    private static final long serialVersionUID = 313598288;

    /**
     * The reference instance of <code>unischema</code>
     */
    public static final Unischema UNISCHEMA = new Unischema();

    /**
     * The table <code>unischema.Assistenten</code>.
     */
    public final Assistenten ASSISTENTEN = de.tum.jk.orm.pojos.unischema.tables.Assistenten.ASSISTENTEN;

    /**
     * The table <code>unischema.hoeren</code>.
     */
    public final Hoeren HOEREN = de.tum.jk.orm.pojos.unischema.tables.Hoeren.HOEREN;

    /**
     * The table <code>unischema.Professoren</code>.
     */
    public final Professoren PROFESSOREN = de.tum.jk.orm.pojos.unischema.tables.Professoren.PROFESSOREN;

    /**
     * The table <code>unischema.pruefen</code>.
     */
    public final Pruefen PRUEFEN = de.tum.jk.orm.pojos.unischema.tables.Pruefen.PRUEFEN;

    /**
     * The table <code>unischema.Studenten</code>.
     */
    public final Studenten STUDENTEN = de.tum.jk.orm.pojos.unischema.tables.Studenten.STUDENTEN;

    /**
     * The table <code>unischema.voraussetzen</code>.
     */
    public final Voraussetzen VORAUSSETZEN = de.tum.jk.orm.pojos.unischema.tables.Voraussetzen.VORAUSSETZEN;

    /**
     * The table <code>unischema.Vorlesungen</code>.
     */
    public final Vorlesungen VORLESUNGEN = de.tum.jk.orm.pojos.unischema.tables.Vorlesungen.VORLESUNGEN;

    /**
     * No further instances allowed
     */
    private Unischema() {
        super("unischema", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Assistenten.ASSISTENTEN,
            Hoeren.HOEREN,
            Professoren.PROFESSOREN,
            Pruefen.PRUEFEN,
            Studenten.STUDENTEN,
            Voraussetzen.VORAUSSETZEN,
            Vorlesungen.VORLESUNGEN);
    }
}
